-- Sets the configuration for pop-up headlights for a vehicle model.
-- @module fivem
-- @submodule unique
-- @link https://wiki.fivem.net/wiki/SetModelHeadlightConfiguration
-- @usage SetModelHeadlightConfiguration('ruiner2', 120.0, 37.5, false)
-- @usage SetModelHeadlightConfiguration('tropos', 30.0, 40.0, false)
-- @param modelHash Model
-- @param rotationPerSecond float
-- @param rotation float
-- @param invertRotation boolean
-- @return void
function SetModelHeadlightConfiguration(modelHash, rotationPerSecond, rotation, invertRotation) end